#!/bin/bash

echo "🔑 Guía para obtener Docker Hub Access Token"
echo "=========================================="
echo ""
echo "1. Ve a: https://hub.docker.com/settings/security"
echo "2. Inicia sesión con tu cuenta de Docker Hub"
echo "3. Haz clic en 'New Access Token'"
echo "4. Dale un nombre descriptivo (ej: 'github-actions-flota')"
echo "5. Selecciona permisos: Read, Write, Delete"
echo "6. Copia el token generado (solo se muestra una vez)"
echo ""
echo "📝 Una vez que tengas el token:"
echo "- Ve a tu repo en GitHub"
echo "- Settings → Secrets and variables → Actions"
echo "- New repository secret:"
echo "  • Name: DOCKER_HUB_TOKEN"
echo "  • Value: [pega tu token aquí]"
echo ""
echo "También necesitarás configurar:"
echo "- DOCKER_HUB_USERNAME: tu nombre de usuario de Docker Hub"
echo ""
echo "⚠️  IMPORTANTE:"
echo "- Guarda el token en un lugar seguro"
echo "- El token solo se muestra una vez al crearlo"
echo "- Si lo pierdes, crea uno nuevo"
echo ""
echo "🔄 Alternativa: Usar GitHub Container Registry (recomendado)"
echo "- No necesitas token adicional"
echo "- Usa el GITHUB_TOKEN que ya tienes"
echo "- Las imágenes se almacenan en ghcr.io"
