version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flota_postgres
    environment:
      POSTGRES_DB: flota_db
      POSTGRES_USER: flota_user
      POSTGRES_PASSWORD: flota_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
