version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: flota_demo
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo_user -d flota_demo"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://demo_user:demo_password@db:5432/flota_demo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../apps/backend:/app
    command: uvicorn src.presentation.api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ../apps/web:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  postgres_data:
