---
name: Documentation
description: Report documentation issues or request improvements
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Issue

        Help us improve our documentation! Please fill out the information below.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Outdated documentation
        - Incorrect documentation
        - Unclear documentation
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: What's wrong with the documentation?
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation located?
      placeholder: e.g., README.md, CONTRIBUTING.md, specific file path
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does the current documentation say?
      placeholder: Copy the current text here

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What should the documentation say instead?
      placeholder: Suggest the improved text

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this documentation fix?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
      placeholder: Any additional information that might be helpful
