name: ✨ Feature
description: Propón una mejora
labels: [enhancement]
body:
  - type: textarea
    id: value
    attributes:
      label: Valor para el usuario
      description: ¿Qué problema resuelve?
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación (Gherkin)
      placeholder: |
        Dado...
        Cuando...
        Entonces...